remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

theme_config:
  appearance: "dark"

title: Dog Vs Cat
description: Some basic classification of pets

author:
  name: Victor Ajayi
