remote_theme: riggraz/no-style-please
plugins:
- jekyll-remote-theme

theme_config:
  appearance: "light"

title: Pet Classifier
description: Some basic classification of pets

author:
  name: Victor Ajayi
